meta:
  stage: .pre
  tags: [shell]
  variables:
    GIT_DEPTH: 1000
  script:
    - echo "OGS_VERSION=${CI_COMMIT_TAG:-`git describe --tags --long --dirty --always`}" >> build.env
    - cat build.env
  artifacts:
    reports:
      dotenv: build.env

meta_container:
  stage: .pre
  rules:
    - if: '$CI_PROJECT_NAMESPACE != "ogs"'
      changes:
      - ThirdParty/container-maker
      - scripts/ci/jobs/build_image.yml
  script:
    - echo "CONTAINER_GCC_IMAGE=$CI_REGISTRY_IMAGE/gcc:$CI_COMMIT_REF_SLUG" >> build.env
    - echo "CONTAINER_GCC_GUI_IMAGE=$CI_REGISTRY_IMAGE/gcc-gui:$CI_COMMIT_REF_SLUG" >> build.env
    - echo "CONTAINER_CLANG_IMAGE=$CI_REGISTRY_IMAGE/clang:$CI_COMMIT_REF_SLUG" >> build.env
    - cat build.env
  artifacts:
    reports:
      dotenv: build.env
